"""empty message

Revision ID: 05d09012c191
Revises: de3d9574596e
Create Date: 2022-08-19 21:59:38.191768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d09012c191'
down_revision = 'de3d9574596e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'venue_id')
    )
    op.drop_table('test')
    op.add_column('Artist', sa.Column('website_link', sa.String(length=200), nullable=True))
    op.add_column('Artist', sa.Column('s_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=200), nullable=True))
    op.add_column('Venue', sa.Column('s_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'description')
    op.drop_column('Venue', 's_talent')
    op.drop_column('Venue', 'website_link')
    op.drop_column('Artist', 'description')
    op.drop_column('Artist', 's_venue')
    op.drop_column('Artist', 'website_link')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.drop_table('shows')
    # ### end Alembic commands ###
