"""empty message

Revision ID: ff82921a7a89
Revises: 05d09012c191
Create Date: 2022-08-19 22:12:49.255611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff82921a7a89'
down_revision = '05d09012c191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'datetime')
    # ### end Alembic commands ###
